# Generated by Django 2.2.9 on 2020-01-06 14:07

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Cropping_Autocomplete_Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('image', image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='uploaded_images', verbose_name='image')),
                ('image_cropped', image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropped')),
            ],
        ),
    ]
